### ISSUE TITLE
remove status ('alpha', 'beta', 'stable' ) 

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-api#15] opened 2020-03-28 08:57 UTC
We should not classify services into this 3 categories.
We should also remove the marathon label "ONYXIA_STATUS": "" for self services

**Comment by Donatien26** [comment] 2020-03-30 12:37
maybe close this issue ? @olevitt

**Comment by olevitt** [comment] 2020-04-01 09:42
This looks mostly like a duplicate of #16   + removing `ONYXIA_STATUS` related code

**Comment by olevitt** [comment] 2020-04-11 14:53
Fixed by #30

**Closed by olevitt** 2020-04-11 14:53 UTC
Labels: good first issue
